const mockCenters = [
  {
    id: 1,
    name: "Common Service Center - Gandhinagar",
    type: "CSC",
    address: "Sector 21, Gandhinagar, Gujarat - 382021",
    phone: "+91-79-23260000",
    services: ["Application submission", "Document verification", "eKYC"],
    distance: "0.7 km",
    rating: 4.3,
  },
  {
    id: 2,
    name: "Post Office - Jayanagar",
    type: "Post Office",
    address: "4th Block, Jayanagar, Bengaluru, Karnataka - 560041",
    phone: "+91-80-26545678",
    services: ["Pension disbursement", "Insurance", "Money orders"],
    distance: "1.1 km",
    rating: 4.1,
  },
  {
    id: 3,
    name: "Gramin Bank - Amethi",
    type: "Bank",
    address: "Main Road, Amethi, Uttar Pradesh - 227405",
    phone: "+91-535-2244556",
    services: ["Account opening", "Direct Benefit Transfer", "PMJDY"],
    distance: "2.5 km",
    rating: 4.4,
  },
  {
    id: 4,
    name: "Block Office - Ranchi Rural",
    type: "Government Office",
    address: "Ormanjhi Block, Ranchi, Jharkhand - 835219",
    phone: "+91-651-2556677",
    services: ["Ration card", "Migrant support", "Housing application"],
    distance: "1.9 km",
    rating: 4.2,
  },
  {
    id: 5,
    name: "Employment Exchange - Guwahati",
    type: "Employment Office",
    address: "Bamunimaidam, Guwahati, Assam - 781021",
    phone: "+91-361-2451122",
    services: ["Job registration", "Skill training", "Job fairs"],
    distance: "3.4 km",
    rating: 4.0,
  },
  {
    id: 6,
    name: "Mahila Sewa Kendra - Ujjain",
    type: "WCD Center",
    address: "Dewas Road, Ujjain, Madhya Pradesh - 456001",
    phone: "+91-734-2516622",
    services: ["Beti Bachao", "Widow pension", "Nutrition aid"],
    distance: "0.9 km",
    rating: 4.5,
  },
  {
    id: 7,
    name: "CSC - Vellore",
    type: "CSC",
    address: "Anna Salai, Vellore, Tamil Nadu - 632001",
    phone: "+91-416-2223377",
    services: ["Aadhaar update", "PAN card", "PM-KISAN help"],
    distance: "1.2 km",
    rating: 4.4,
  },
  {
    id: 8,
    name: "Post Office - Anjuna",
    type: "Post Office",
    address: "Anjuna, North Goa, Goa - 403509",
    phone: "+91-832-2278890",
    services: ["Speed post", "Financial services", "Old age pension"],
    distance: "0.8 km",
    rating: 4.1,
  },
  {
    id: 9,
    name: "Gram Panchayat Office - Chhindwara",
    type: "Government Office",
    address: "Ward No. 3, Chhindwara, Madhya Pradesh - 480001",
    phone: "+91-7162-220055",
    services: ["NREGA work", "BPL list update", "Water connection"],
    distance: "2.8 km",
    rating: 3.9,
  },
  {
    id: 10,
    name: "Welfare Center - Bhubaneshwar",
    type: "Welfare Office",
    address: "Unit 4, Bhubaneshwar, Odisha - 751001",
    phone: "+91-674-2537788",
    services: ["Disability pension", "Scholarships", "Scheme info"],
    distance: "1.5 km",
    rating: 4.3,
  },
  {
    id: 11,
    name: "CSC - Barmer",
    type: "CSC",
    address: "Station Road, Barmer, Rajasthan - 344001",
    phone: "+91-2982-252525",
    services: ["Ayushman card", "Labor card", "Gas subsidy"],
    distance: "3.1 km",
    rating: 4.0,
  },
  {
    id: 12,
    name: "Bank of Maharashtra - Solapur",
    type: "Bank",
    address: "Budhwar Peth, Solapur, Maharashtra - 413002",
    phone: "+91-217-2626352",
    services: ["Mudra loans", "Savings account", "PMAY"],
    distance: "1.7 km",
    rating: 4.2,
  },
  {
    id: 13,
    name: "Women Help Center - Kozhikode",
    type: "WCD Center",
    address: "Mavoor Road, Kozhikode, Kerala - 673004",
    phone: "+91-495-2766677",
    services: ["SHG training", "Women helpline", "Scheme application"],
    distance: "1.0 km",
    rating: 4.6,
  },
  {
    id: 14,
    name: "Employment Office - Patna",
    type: "Employment Office",
    address: "Bailey Road, Patna, Bihar - 800001",
    phone: "+91-612-2222333",
    services: ["Skill India", "Rozgar Mela", "Registration"],
    distance: "2.3 km",
    rating: 4.1,
  },
  {
    id: 15,
    name: "Panchayat Bhawan - Kullu",
    type: "Government Office",
    address: "Naggar Road, Kullu, Himachal Pradesh - 175101",
    phone: "+91-1902-223388",
    services: ["Housing support", "Yojana info", "Certificates"],
    distance: "1.3 km",
    rating: 4.0,
  },
  {
    id: 16,
    name: "Sewa Kendra - Ludhiana",
    type: "CSC",
    address: "Model Town, Ludhiana, Punjab - 141002",
    phone: "+91-161-2438888",
    services: ["Birth cert.", "Driving license", "Land records"],
    distance: "2.6 km",
    rating: 4.4,
  },
];

export default mockCenters;
