import { Sprout, Heart, Building, GraduationCap, Users, Handshake, IndianRupee, Briefcase } from "lucide-react";

const mockSchemes = [
  {
    id: 1,
    name: "PM-KISAN",
    nameHi: "पीएम-किसान",
    category: "agriculture",
    description: "Income support for farmers",
    descriptionHi: "किसानों के लिए आय सहायता",
    benefit: "₹6,000 per year",
    sdg: [1, 2],
    eligibility: ["Farmer", "Land ownership", "Below income threshold"],
    icon: Sprout,
    color: "green",
    applicationUrl: "https://pmkisan.gov.in/", 
  },
  {
    id: 2,
    name: "Ayushman Bharat",
    nameHi: "आयुष्मान भारत",
    category: "health",
    description: "Health insurance coverage",
    descriptionHi: "स्वास्थ्य बीमा कवरेज",
    benefit: "₹5 lakh coverage",
    sdg: [3],
    eligibility: ["Income criteria", "SECC database", "No existing insurance"],
    icon: Heart,
    color: "red",
    applicationUrl: "https://pmjay.gov.in/", 
  },
  {
    id: 3,
    name: "Samagra Shiksha",
    nameHi: "समग्र शिक्षा",
    category: "education",
    description: "School education support",
    descriptionHi: "स्कूली शिक्षा सहायता",
    benefit: "Free education & materials",
    sdg: [4],
    eligibility: ["School age", "Government school", "Regular attendance"],
    icon: GraduationCap,
    color: "blue",
    applicationUrl: "https://samagra.education.gov.in/",
  },
  {
    id: 4,
    name: "PM Awas Yojana",
    nameHi: "पीएम आवास योजना",
    category: "social",
    description: "Housing for all",
    descriptionHi: "सभी के लिए आवास",
    benefit: "Subsidized housing",
    sdg: [11],
    eligibility: ["Income limit", "No pucca house", "Not availed before"],
    icon: Building,
    color: "orange",
    applicationUrl: "https://pmaymis.gov.in/", 
  },
  {
    id: 5,
    name: "MGNREGA",
    nameHi: "मनरेगा",
    category: "social",
    description: "Employment guarantee",
    descriptionHi: "रोजगार गारंटी",
    benefit: "100 days guaranteed work",
    sdg: [1, 8],
    eligibility: ["Adult", "Rural area", "Willing to work"],
    icon: Users,
    color: "purple",
    applicationUrl: "https://nrega.nic.in/", 
  },
  {
    id: 6,
    name: "Ujjwala Yojana",
    nameHi: "उज्ज्वला योजना",
    category: "women",
    description: "Free LPG connections to women",
    descriptionHi: "महिलाओं को मुफ्त एलपीजी कनेक्शन",
    benefit: "Free LPG + subsidy",
    sdg: [5, 7],
    eligibility: ["BPL family", "Woman above 18", "No prior LPG connection"],
    icon: Handshake,
    color: "pink",
    applicationUrl: "https://pmuy.gov.in/", 
  },
  {
    id: 7,
    name: "Beti Bachao Beti Padhao",
    nameHi: "बेटी बचाओ बेटी पढ़ाओ",
    category: "education",
    description: "Promotes girl child education",
    descriptionHi: "बेटियों की शिक्षा को बढ़ावा",
    benefit: "Awareness + scholarships",
    sdg: [4, 5],
    eligibility: ["Girl child", "School enrollment", "Parental consent"],
    icon: GraduationCap,
    color: "rose",
    applicationUrl: "https://icds.gov.in/en/schemes", 
  },
  {
    id: 8,
    name: "National Scholarship Portal",
    nameHi: "राष्ट्रीय छात्रवृत्ति पोर्टल",
    category: "education",
    description: "Centralized scholarship portal",
    descriptionHi: "छात्रवृत्ति के लिए केंद्रीकृत पोर्टल",
    benefit: "₹10,000 to ₹50,000",
    sdg: [4],
    eligibility: ["Meritorious students", "Income below ₹8L", "Govt schools/colleges"],
    icon: IndianRupee,
    color: "teal",
    applicationUrl: "https://scholarships.gov.in/", 
  },
  {
    id: 9,
    name: "Stand Up India",
    nameHi: "स्टैंड अप इंडिया",
    category: "entrepreneurship",
    description: "Loans for women & SC/ST entrepreneurs",
    descriptionHi: "महिलाओं और अनुसूचित जाति/जनजाति के लिए ऋण",
    benefit: "Loans ₹10L–₹1Cr",
    sdg: [8, 9],
    eligibility: ["SC/ST/Women", "Greenfield enterprise", "Above 18 years"],
    icon: Briefcase,
    color: "amber",
    applicationUrl: "https://www.standupmitra.in/", 
  },
];


export default mockSchemes;